name: Terraform CI/CD with GitHub Actions

on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:
    branches:
      - main
      - dev
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/staging/prod)"
        required: true
        default: dev

jobs:
  terraform:
    name: Deploy to ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}
    runs-on: ubuntu-latest

    env:
      # Xác định môi trường (chữ thường)
      ENV_LOWER: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}
      # Ánh xạ sang tên thư mục thực tế (chữ hoa: Dev, Staging, Prod)
      ENVIRONMENT: ${{ env.ENV_LOWER == 'dev' && 'Dev' || env.ENV_LOWER == 'staging' && 'Staging' || env.ENV_LOWER == 'prod' && 'Prod' || 'Dev' }}

    defaults:
      run:
        working-directory: ./env/${{ env.ENVIRONMENT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug working directory
        run: |
          pwd
          ls -la
        working-directory: ./env/${{ env.ENVIRONMENT }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve