name: Terraform CI/CD with GitHub Actions

on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:
    branches:
      - main
      - dev
      - staging
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/staging/prod)"
        required: true
        default: dev

jobs:
  terraform:
    name: Deploy to Environment
    runs-on: ubuntu-latest

    env:
      # Mặc định ENVIRONMENT là 'dev', sẽ được ghi đè nếu cần
      ENVIRONMENT: dev
      # Nếu sự kiện là workflow_dispatch, sử dụng giá trị từ inputs.environment
      INPUT_ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || '' }}
      # Nếu không phải workflow_dispatch, ánh xạ dựa trên nhánh
      BRANCH_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' || 'dev' }}
      # Ghi đè ENVIRONMENT nếu INPUT_ENV hoặc BRANCH_ENV có giá trị
      ENVIRONMENT_OVERRIDE: ${{ env.INPUT_ENV != '' && env.INPUT_ENV || env.BRANCH_ENV }}

    defaults:
      run:
        working-directory: ./env/${{ env.ENVIRONMENT_OVERRIDE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug environment variable
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Input environment: ${{ github.event.inputs.environment }}"
          echo "ENVIRONMENT_OVERRIDE is set to: ${{ env.ENVIRONMENT_OVERRIDE }}"
          echo "Working directory will be: ./env/${{ env.ENVIRONMENT_OVERRIDE }}"

      - name: Debug working directory
        run: |
          pwd
          ls -la

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve